### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [BUIQUOCDAT1281997/Price-List#1]
1. Классы в Java принято именовать с большой буквы.
2. Класс `products` логичнее назвать `Product`, он представляет только один продукт.
3. В половине методов вы ищете продукт по коду, а в другой половине методов - по имени. Предполагается, что код уникально идентифицирует продукт, а имя служит дополнительной информацией.
4. Есть ощущение, что вы используете `Map` совершенно не по назначению. `Map` служит для того, чтобы по ключу эффективно получать значение, а вы везде перебираете все ключи и значения из `Map`. Предлагаю сделать следующее: сделать Map из кода товара в  объект класса `Product`. В таком случае вы сможете эффективно получать товар по его коду с помощью метода `get`. Цену на товар можно внести в сам товар или (как альтернатива) обернуть её вместе с товаром в класс `PriceListItem`.
5. Кое-где нарушается инкапсуляция. Так, например, можно добавить товар в прайс-лист, а потом сделать `setName` на товаре, тем самым изменив содержимое прайс-листа минуя API прайс-листа. Предлагаю в классах `products` и `price` сделать все поля, которые возможно неизменяемыми (рубли и копейки в цене, код у продукта и т. п.), а где невозможно, при необходимости копировать объекты при добавлении в прайс-лист или при возвращении значения пользователю.
6. Поле `list` в классе `priceList` лучше сделать приватным и добавить тривиальные методы для поиска товара по коду, получения размера прайс-листа и т. п.
7. Пожалуйста разберитесь, как работать c git по какому-нибудь учебнику в интернете. Если вы будете удалять и пересоздавать репозиторий на каждую версию, это никуда не годится.

**Comment by BUIQUOCDAT1281997** [comment]
Мне понятно. Спасибо за замечания. Я попытаюсь исправить .

**Comment by gagarski** [comment]
1. Классы вы переименовали, а названия файлов отличаются регистром от названий классов. На платформах с регистрозависимыми названиями файлов ваш код не скомпилируется.
2. Было бы неплохо добавить конструктор, создающий пустой прайс-лист
3. При создании объекта вы используете ссылку на хэш-таблицу, а в геттере возвращаете её. Таким образом вы можете поменять состояние вашего прайс-листа через эту таблицу. При создании лучше сделать копию, а в геттере либо копию, либо обернуть возвращаемое значение в `Collections.unmodifiableMap` (постарайтесь понять, в чём разница этих подходов)
4. У `PriceListItem` отсутствуют `equals` и `hashCode`.
5. `equals` у `PriceList` реализован неверно. Если создать одинаковые прайс-листы, то они не будут равны. `hashCode` чисто технически корректный, но плохой, у прайс-листов одинаковой длины будет одинаковый хэш-код. 
5. Тестами покрыта не вся функциональность.

**Comment by BUIQUOCDAT1281997** [comment]
я исправил

**Comment by gagarski** [comment]
У вас теперь есть метод `equals` и вроде даже правильный. Попрацьте теперь тесты, в которых вы сравниваете строковые представления прайс-листа.

**Comment by BUIQUOCDAT1281997** [comment]
Please..
Вы можете заранее проверить это задание?
Я очень хочу сдать это задание до 15.4.2018.
тесты я уже исправил.

**Comment by gagarski** [comment]
Не исправили. Всё ещё сначала делаете `toString`, а потом сравниваете. Нужно сравнивать объекты на equals, а не их строковые представления.

**Comment by BUIQUOCDAT1281997** [comment]
я исправил. поссмотрите пожалуйста
